### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by timveletta**
Amazing project please merge - I want free tshort

### CODE REVIEW

**Review by jgunnink — APPROVED** [review]

**Review by bryan-yu — APPROVED** [review]

**Review by t04glovern — APPROVED** [review]

**Comment by t04glovern** [comment]
LGTM

**Comment by Hamo69** [comment]
this PR has no tests. Please add the test prior to merge

**Comment by t04glovern** [comment]
> this PR has no tests. Please add the test prior to merge

I have added test https://github.com/MechanicalRock/mechanicalrock.github.io/commit/2d7e03a64e0c84566ba16dee8c9f55ab988c38dd

**Comment by t04glovern** [comment]
> this is an amazing test, but I'm not sure it really _asserts_ in the way I _expect_

i require jira ticket and t-shirt sizes

**Comment by SrzStephen** [comment]
> > this PR has no tests. Please add the test prior to merge
> 
> I have added test [2d7e03a](https://github.com/MechanicalRock/mechanicalrock.github.io/commit/2d7e03a64e0c84566ba16dee8c9f55ab988c38dd)

LGTM

**Pull request merged**
